name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  test-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs-version:
          - 27.1
          - 27.2
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: actions/checkout@v2
    - name: Copy configuration files
      run: sh ./bin/copy_config.sh

    - name: Test startup
      run: make startup

    - name: Test speed
      run: make speed

  test-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        emacs-version:
          - 27.1
          - 27.2
          - snapshot
    steps:
    - uses: jcs090218/setup-emacs-windows@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: actions/checkout@v2
    - name: Copy configuration files
      run: ./bin/copy_config.bat

    - name: Test startup
      run: make startup

    - name: Test speed
      run: make speed
