name: Speed

on:
  workflow_run:
    workflows: ["Startup"]
    types:
      - completed
  workflow_dispatch:

env:
  BIN_REPO: 'jcs-emacs/binaries'

jobs:
  speed:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 28.1
    steps:
    - name: Checkout binaries repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.BIN_REPO }}
        persist-credentials: false
        fetch-depth: 0

    - name: Create LFS file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

    - name: Restore LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

    - name: Git LFS Pull
      run: |
        git lfs pull
        git add .
        git reset --hard

    - name: Extract zipped .emacs.d
      run: tar -xvf main.tar -C $HOME

    - uses: purcell/setup-emacs@master
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      with:
        version: ${{ matrix.emacs-version }}

    - uses: jcs090218/setup-emacs-windows@master
      if: matrix.os == 'windows-latest'
      with:
        version: ${{ matrix.emacs-version }}

    - uses: actions/checkout@v2

    # Make sure we neve accidently startup in speed phase
    - run: make startup

    - name: Test speed
      run: make speed

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Push generated badges - speed
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update SVG badges - speed"
        git push
