name: Speed

on:
  workflow_run:
    workflows: ["Startup"]
    types:
      - completed
  workflow_dispatch:

jobs:
  speed:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 28.1
    steps:
    - name: Checkout binaries repository
      uses: actions/checkout@v3
      with:
        repository: 'jcs-emacs/binaries'

    - name: Extract zipped .emacs.d
      run: tar -xvf ${{ matrix.os }}.${{ matrix.emacs-version }}.jcs-emacs.zip -C ~/.emacs.d

    - uses: actions/checkout@v2

    - name: Test speed
      run: make speed

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Push generated badges - speed
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update SVG badges - speed"
        git push
