name: Startup

on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - '**.el'
      - lisp/**
      - site-lisp/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO_BIN: 'jcs-emacs/binaries'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version: [28.1]
        experimental: [false]
        include:
        - os: ubuntu-latest
          emacs-version: snapshot
          experimental: true
        - os: macos-latest
          emacs-version: snapshot
          experimental: true
        - os: windows-latest
          emacs-version: snapshot
          experimental: true

    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: actions/checkout@v2

    - name: Copy configuration files
      run: |
        chmod -R 777 ./
        make copy_config

    - name: Test startup
      run: make startup

    - name: Checkout binaries repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPO_BIN }}
        persist-credentials: false
        fetch-depth: 0

    - name: Create LFS file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

    - name: Restore LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

    - name: Git LFS Pull
      continue-on-error: true
      run: |
        git lfs pull
        git add .
        git reset --hard

    - name: Remove before creating tar file
      uses: JesseTG/rm@v1.0.2
      with:
        path: main.tar

    - name: Zipping .emacs.d
      run: tar -C $HOME -cvf main.tar .emacs.d

    - name: Commit zipped .emacs.d
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update .emacs.d - main.tar
        commit_user_name: github-actions
        commit_user_email: github-actions@github.com

    - uses: Wandalen/wretry.action@v1.0.11
      with:
        action: jcs090218/github-push-action@master
        with: |
          repository: ${{ env.REPO_BIN }}
          github_token: ${{ secrets.PAT }}
          branch: master
        attempt_limit: 7
