name: Startup

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'
  workflow_dispatch:

env:
  BIN_REPO: 'jcs-emacs/binaries'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 28.1
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      with:
        version: ${{ matrix.emacs-version }}

    - uses: jcs090218/setup-emacs-windows@master
      if: matrix.os == 'windows-latest'
      with:
        version: ${{ matrix.emacs-version }}

    - uses: actions/checkout@v2

    - name: Copy configuration files (Unix)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: sh ./test/startup/copy_config.sh

    - name: Copy configuration files (Windows)
      if: matrix.os == 'windows-latest'
      run: ./test/startup/copy_config.bat

    - name: Test startup
      run: make startup

    - name: Checkout binaries repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.BIN_REPO }}
        persist-credentials: false
        fetch-depth: 0

    - name: Create LFS file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

    - name: Restore LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

    - name: Git LFS Pull
      run: |
        git lfs pull
        git add .
        git reset --hard

    - name: Remove before creating tar file
      uses: JesseTG/rm@v1.0.2
      with:
        path: main.tar

    - name: Zipping .emacs.d
      run: tar -C $HOME -cvf main.tar .emacs.d

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config receive.denynonfastforwards false

    - name: Commit zipped .emacs.d
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update .emacs.d - main.tar"

    - name: Push zipped .emacs.d
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.BIN_REPO }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: master

    - name: Retry push 1
      continue-on-error: true
      run: git pull --rebase
    - name: Push
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.BIN_REPO }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: master

    - name: Retry push 2
      continue-on-error: true
      run: git pull --rebase
    - name: Push
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.BIN_REPO }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: master

    - name: Retry push 3
      continue-on-error: true
      run: git pull --rebase
    - name: Push
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.BIN_REPO }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: master

    - name: Retry push 4
      continue-on-error: true
      run: git pull --rebase
    - name: Push
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.BIN_REPO }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: master

    - name: Retry push 5
      continue-on-error: true
      run: git pull --rebase
    - name: Push
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.BIN_REPO }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: master

    - name: Retry push 6
      continue-on-error: true
      run: git pull --rebase
    - name: Push
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.BIN_REPO }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: master

    - name: Retry push 7
      continue-on-error: true
      run: git pull --rebase
    - name: Push
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.BIN_REPO }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: master
